 # incidencia de Covid19 históricos por estado

In [2]:
# Librerías estándar de análisis de datos
import numpy as np
import pandas as pd
import request 

# Librerías de visualización
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
# URL de la API en formato CSV
HISTORIC_ALL_STATES = "https://api.covidtracking.com/v1/states/daily.csv"

def obtener_datos_csv(url):
    try:
        df = pd.read_csv(url)
        return df
    except Exception as e:
        print(f"Error al obtener datos de {url}: {e}")
        return None
# Obtener datos en formato CSV
df = obtener_datos_csv(HISTORIC_ALL_STATES)
# Imprimir los primeros registros de los datos
if df is not None:
    print("data cargada")
else:
    print("No se pudieron obtener los datos")

data cargada

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20780 entries, 0 to 20779
Data columns (total 56 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   date                         20780 non-null  int64
 1   state                        20780 non-null  object
 2   positive                     20592 non-null  float64
 3   probableCases                9271 non-null   float64
 4   negative                     13290 non-null  float64
 5   pending                      2138 non-null   float64
 6   totalTestResultsSource       20780 non-null  object
 7   totalTestResults             20614 non-null  float64
 8   hospitalizedCurrently        17339 non-null  float64
 9   hospitalizedCumulative       12382 non-null  float64
 10  inIcuCurrently               11636 non-null  float64
 11  inIcuCumulative              3789 non-null   float64
 12  onVentilatorCurrently        9126 non-null   float64
 13  onVentilatorCumulative       1290 non-null   float64
 14  recovered                    12003 non-null  float64
 15  lastUpdateEt                 20164 non-null  object
 16  dateModified                 20164 non-null  object
 17  checkTimeEt                  20164 non-null  object
 18  death                        19930 non-null  float64
 19  hospitalized                 12382 non-null  float64
 20  hospitalizedDischarged       3070 non-null   float64
 21  dateChecked                  20164 non-null  object
 22  totalTestsViral              14516 non-null  float64
 23  positiveTestsViral           8958 non-null   float64
 24  negativeTestsViral           5024 non-null   float64
 25  positiveCasesViral           14246 non-null  float64
 26  deathConfirmed               9422 non-null   float64
 27  deathProbable                7593 non-null   float64
 28  totalTestEncountersViral     5231 non-null   float64
 29  totalTestsPeopleViral        9197 non-null   float64
 30  totalTestsAntibody           4789 non-null   float64
 31  positiveTestsAntibody        3346 non-null   float64
 32  negativeTestsAntibody        1458 non-null   float64
 33  totalTestsPeopleAntibody     2200 non-null   float64
 34  positiveTestsPeopleAntibody  1094 non-null   float64
 35  negativeTestsPeopleAntibody  972 non-null    float64
 36  totalTestsPeopleAntigen      999 non-null    float64
 37  positiveTestsPeopleAntigen   633 non-null    float64
 38  totalTestsAntigen            3421 non-null   float64
 39  positiveTestsAntigen         2233 non-null   float64
 40  fips                         20780 non-null  int64
 41  positiveIncrease             20780 non-null  int64
 42  negativeIncrease             20780 non-null  int64
 43  total                        20780 non-null  int64
 44  totalTestResultsIncrease     20780 non-null  int64
 45  posNeg                       20780 non-null  int64
 46  dataQualityGrade             0 non-null      float64
 47  deathIncrease                20780 non-null  int64
 48  hospitalizedIncrease         20780 non-null  int64
 49  hash                         20780 non-null  object
 50  commercialScore              20780 non-null  int64
 51  negativeRegularScore         20780 non-null  int64
 52  negativeScore                20780 non-null  int64
 53  positiveScore                20780 non-null  int64
 54  score                        20780 non-null  int64
 55  grade                        0 non-null      float64
dtypes: float64(35), int64(14), object(7)
memory usage: 8.9+ MB

In [18]:
df.head()

,date,state,positive,probableCases,negative,pending,totalTestResultsSource,totalTestResults,hospitalizedCurrently,hospitalizedCumulative,...,dataQualityGrade,deathIncrease,hospitalizedIncrease,hash,commercialScore,negativeRegularScore,negativeScore,positiveScore,score,grade
0,20210307,AK,56886.0,NaN,NaN,NaN,totalTestsViral,1731628.0,33.0,1293.0,...,NaN,0,0,dc4bccd4bb885349d7e94d6fed058e285d4be164,0,0,0,0,0,NaN
1,20210307,AL,499819.0,107742.0,1931711.0,NaN,totalTestsPeopleViral,2323788.0,494.0,45976.0,...,NaN,-1,0,997207b430824ea40b8eb8506c19a93e07bc972e,0,0,0,0,0,NaN
2,20210307,AR,324818.0,69092.0,2480716.0,NaN,totalTestsViral,2736442.0,335.0,14926.0,...,NaN,22,11,50921aeefba3e30d31623aa495b47fb2ecc72fae,0,0,0,0,0,NaN
3,20210307,AS,0.0,NaN,2140.0,NaN,totalTestsViral,2140.0,NaN,NaN,...,NaN,0,0,f77912d0b80d579fbb6202fa1a90554fc4dc1443,0,0,0,0,0,NaN
4,20210307,AZ,826454.0,56519.0,3073010.0,NaN,totalTestsViral,7908105.0,963.0,57907.0,...,NaN,5,44,0437a7a96f4471666f775e63e86923eb5cbd8cdf,0,0,0,0,0,NaN